[package]
name = "rsess-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
jemalloc-ctl = "0.5.4"
jemallocator = "0.5.4"
json = "0.12.4"
rsess = "0.1.0"
rug = "1.20.1"
